### ISSUE TITLE
Form not working..

### ISSUE THREAD

**Issue by rhukster** [tranduyhung/grav-skeleton-x-corporation#1]
Had a user on gitter using this skeleton and the form didn't work. I confirmed.

1) you are copying the form twig and changing it.  it's out of date or something because it was not working, I changed the `contact.html.twig` to include the standard form twig (from the plugin):

```
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% include 'forms/default/form.html.twig' %}
    </div>
</div>
```

2) Also the form definition was not working as the display page didn't exist. I changed to this:

```
    process:
        - email:
            from: "{{ config.plugins.email.from }}"
            to:
              - "{{ config.plugins.email.from }}"
            subject: "[Contact] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
        - save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        - message: 'Thank you from your Feedback!'
        - reset: true
```

3) You should set `cache_enable: false` on the modular.md page because if you have cache on, it will cache the form only and will not handle any responses.
