### ISSUE TITLE
Carousel on high res screens

### ISSUE THREAD

**Issue by mhingston** [tranduyhung/grav-skeleton-x-corporation#4]
Hi, thanks for the great theme.

I've noticed that the carousel is clipping on high res screens (see attached screenshot).

![screenshot from 2016-12-21 11-54-04](https://cloud.githubusercontent.com/assets/9764437/21388601/e2c430e0-c774-11e6-8133-96fcb0a7d55a.jpg)

**Comment by tranduyhung** [comment]
Thank you for letting me know! Could you please tell me what the width of your screen is?

**Comment by mhingston** [comment]
Hi,

Screen width: 2021
Screen height: 1136
Native Resolution: 3840 x 2160
DPI: 144

**Comment by evehne** [comment]
Same here, 
on ultra-wide screen 2560x1080
![sans-titre-1](https://user-images.githubusercontent.com/23144992/36416536-8ed415ae-1629-11e8-9e0f-359611c000ec.jpg)

To avoid this effect, image must be a background (no interest to place on img element) like :

```css
.slider-img
{
  display:table;
  position:relative;
  width:100%;
  height:100%;
  background-repeat:no-repeat;
  background-position:center center;
  background-attachment:scroll;
  background-size:cover;
}
```

background-image can be set on div.style ...
