### ISSUE TITLE
Contact forms are send to 'from' address

### ISSUE THREAD

**Issue by kakosNikos** [tranduyhung/grav-skeleton-x-corporation#9]
code from pages/04.contact/modular.md
line: 52

```
    process:
        - email:
            from: "{{ config.plugins.email.from }}"
            to:
              - "{{ config.plugins.email.from }}"
            subject: "[Contact] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
```
